services:
   longitude-one.meta.service:
      resource: '../../src/Service/MetaService.php'
   longitude-one.meta.extension:
      resource: '../../src/Twig/LongitudeOneMetaExtension.php'
      arguments: '@longitude-one.meta.service'
